export const topicData = [
  {
    name: "Fun",
    question: "Which type of “Fun” content do you want to create?",
    options: [
      "Board games revival",
      "Comedy trends",
      "Amusement parks",
      "Street performances",
      "Online challenges",
      "Festivals impact",
      "Crafting movement",
      "social gaming",
      "Virtual reality",
    ],
  },
  {
    name: "Education",
    question: "Which type of “Education” content do you want to create?",
    options: [
      "Gamified learning",
      "Education systems",
      "Bilingual benefits",
      "Standardized testing",
      "Arts in schools",
      "Tech bootcamps",
      "Homeschooling dynamics",
      "Mentorship importance",
      "Educational equity",
      "Mobile learning",
    ],
  },
  {
    name: "Sports",
    question: 'Which type of "Sports" content do you want to create?',
    options: [
      "Sports medicine",
      "Team sociology",
      "Olympic economics",
      "Gender parity",
      "Fandom psychology",
      "Extreme sports",
      "Sports business",
      "Youth athletics",
      "Data analytics",
      "Doping ethics",
    ],
  },
  {
    name: "News",
    question: 'Which type of "News" content do you want to create?',
    options: [
      "Citizen journalism",
      "Whistleblower influence",
      "Fake news",
      "Print media survival",
      "Social media news",
      "Cybersecurity news",
      "Democratic media",
      "News deserts",
      "News economics",
      "Broadcast evolution",
    ],
  },
  {
    name: "Investments",
    question: 'Which type of "Investments" content do you want to create?',
    options: [
      "Robo-advising",
      "Geopolitical impacts",
      "Index funds",
      "Real estate trends",
      "Startup investing",
      "Social trading",
      "Tax strategies",
      "Emerging markets",
      "Financial literacy",
      "Pension futures",
    ],
  },
  {
    name: "Facts",
    question: "Which type of “Facts” content do you want to create?",
    options: [
      "Animal oddities",
      "Everyday science",
      "Historical obscurities",
      "Science myths",
      "Human body facts",
      "Oceanic discoveries",
      "Space exploration",
      "Ancient tech",
      "World laws",
      " Bizarre news",
    ],
  },
];
